using System.Globalization;

namespace GroupLab.Cli.Bench;

/// <summary>
/// Where a case files the timings of its own parts, NOTES-FROM-PLANNING.md entry 117 section 4: "stage timings already exist in the stage
/// record; use them rather than inventing a second timing path". An analysis case runs once and hands its stage record over here, so the
/// record carries marker detection, registration and hole detection as rows of their own rather than hidden inside a total.
/// </summary>
public sealed class BenchSink
{
    private readonly Dictionary<string, List<double>> _parts = [];

    /// <summary>One part of this case, by name, in milliseconds.</summary>
    public void Part(string name, double milliseconds)
    {
        if (!_parts.TryGetValue(name, out var times))
        {
            _parts[name] = times = [];
        }

        times.Add(milliseconds);
    }

    /// <summary>Every part filed, in the order first seen, with every run's figure.</summary>
    public IReadOnlyDictionary<string, List<double>> Parts => _parts;

    internal void Clear() => _parts.Clear();
}

/// <summary>
/// One thing the benchmark measures, NOTES-FROM-PLANNING.md entry 117 sections 3a and 4. A case takes nothing from anybody: its material is
/// either committed in the repository or generated by GroupLab itself, so <c>grouplab bench</c> runs on a bare checkout and on CI.
/// <para>
/// <see cref="Covers"/> names the types the case actually exercises, and is what <c>BenchCoverageTests</c> holds the list to: a new public
/// entry point in a measured namespace fails that test rather than quietly going unmeasured, which is the guard section 3a asks for.
/// </para>
/// </summary>
/// <param name="Area">The group the case belongs to in the record.</param>
/// <param name="Name">The case's name in the record, stable, because a record is read as a difference against the last one.</param>
/// <param name="What">One line saying what is being timed, in the terms a person would use.</param>
/// <param name="Run">The work, run once. It may file its parts in the sink, and returns a short note for the record, or null.</param>
/// <param name="Covers">The types this case exercises, by name.</param>
public sealed record BenchCase(string Area, string Name, string What, Func<BenchSink, string?> Run, IReadOnlyList<string> Covers);

/// <summary>
/// Something that can be measured and is not, by name and with its reason, entry 117 section 3b: "exclusion is by name in the record, never
/// by silence". Everything that prints to a device, opens a system dialog, deletes data or reaches the network lives here.
/// </summary>
public sealed record BenchExclusion(string Area, string Name, string Why);

/// <summary>
/// What one case, or one part of a case, measured. The median is the figure, and the low and high are the fastest and slowest run, so a
/// reader can see when a figure is unstable rather than trusting one number.
/// </summary>
public sealed record BenchMeasurement(string Area, string Name, string What, int Runs, double MedianMs, double LowMs, double HighMs, string? Note, string? Failure, bool IsPart = false)
{
    /// <summary>The median with its spread, for the record's table.</summary>
    public string Figure => Failure is not null
        ? "not measured"
        : string.Create(CultureInfo.InvariantCulture, $"{MedianMs:0.0} ({LowMs:0.0} to {HighMs:0.0})");
}
