using System.Globalization;
using System.Text;

namespace GroupLab.Cli.Bench;

/// <summary>
/// The record <c>grouplab bench</c> prints and writes, NOTES-FROM-PLANNING.md entry 117 sections 3 and 4: one table, with the date, the
/// machine, the build and the commit, so a change's effect is a difference between two committed tables rather than an opinion. The worst
/// cases go at the top, because that list is the work queue for the Performance phase.
/// </summary>
public static class BenchReport
{
    /// <summary>The record as Markdown, in the shape docs/PERFORMANCE.md holds.</summary>
    public static string Markdown(IReadOnlyList<BenchMeasurement> measured, IReadOnlyList<BenchExclusion> excluded, BenchMachine machine)
    {
        ArgumentNullException.ThrowIfNull(measured);
        ArgumentNullException.ThrowIfNull(excluded);
        ArgumentNullException.ThrowIfNull(machine);
        var text = new StringBuilder();
        text.Append("## The record\n\n");
        text.Append(CultureInfo.InvariantCulture, $"Measured {machine.Date} on {machine.Name}, {machine.Processors} processors, {machine.Operating}, {machine.Configuration} build, commit {machine.Commit}, {machine.Runs} timed runs of each case after one thrown away.\n\n");
        text.Append("Every figure is milliseconds: the median, and in brackets the fastest and slowest run. **Nothing here has been optimised**: this is the baseline the Performance phase's gate is written from.\n\n");

        text.Append("### The slowest first, which is the work queue\n\n");
        text.Append("| ms, median (low to high) | Case |\n|---|---|\n");
        foreach (var slow in measured.Where(x => x is { IsPart: false, Failure: null }).OrderByDescending(x => x.MedianMs).Take(10))
        {
            text.Append(CultureInfo.InvariantCulture, $"| {slow.Figure} | {slow.Area}: {slow.Name} |\n");
        }

        foreach (var area in measured.Select(x => x.Area).Distinct(StringComparer.Ordinal))
        {
            text.Append(CultureInfo.InvariantCulture, $"\n### {area}\n\n| Case | ms, median (low to high) | What, and what it did |\n|---|---|---|\n");
            foreach (var row in measured.Where(x => string.Equals(x.Area, area, StringComparison.Ordinal)))
            {
                string what = row.Failure is not null ? "**Not measured.** " + row.Failure : row.What + (row.Note is null ? "" : " " + row.Note + ".");
                text.Append(CultureInfo.InvariantCulture, $"| {(row.IsPart ? "&nbsp;&nbsp;" : "")}{row.Name} | {row.Figure} | {what} |\n");
            }
        }

        text.Append("\n### Measured by name, and not measured\n\n");
        text.Append("Entry 117 section 3b: exclusion is by name in the record, never by silence.\n\n| Not measured | Why |\n|---|---|\n");
        foreach (var exclusion in excluded)
        {
            text.Append(CultureInfo.InvariantCulture, $"| {exclusion.Area}: {exclusion.Name} | {exclusion.Why} |\n");
        }

        return text.ToString();
    }

    /// <summary>
    /// Puts a table into the committed record in place, replacing the section of that heading and leaving everything else alone, so a record
    /// is regenerated by a command rather than by pasting. A file that does not have the heading yet gets the section at its end.
    /// </summary>
    public static void Replace(string path, string heading, string section)
    {
        ArgumentNullException.ThrowIfNull(path);
        ArgumentNullException.ThrowIfNull(heading);
        ArgumentNullException.ThrowIfNull(section);
        const string line = "\n";
        string document = File.Exists(path) ? File.ReadAllText(path).ReplaceLineEndings(line) : "";
        string body = section.ReplaceLineEndings(line).TrimEnd('\n');
        int start = document.IndexOf(heading, StringComparison.Ordinal);
        if (start < 0)
        {
            File.WriteAllText(path, document.TrimEnd('\n') + line + line + body + line);
            return;
        }

        int next = document.IndexOf(line + "## ", start + heading.Length, StringComparison.Ordinal);
        string tail = next < 0 ? "" : document[(next + 1)..];
        File.WriteAllText(path, document[..start] + body + line + line + tail);
    }

    /// <summary>One line per case as it finishes, for somebody watching a long run.</summary>
    public static string Line(BenchMeasurement m)
    {
        ArgumentNullException.ThrowIfNull(m);
        string name = (m.IsPart ? "    " : "") + m.Name;
        return string.Create(CultureInfo.InvariantCulture, $"{name,-58} {m.Figure,-24} {(m.Failure is not null ? m.Failure : m.Note ?? "")}");
    }
}

/// <summary>What the record names the measurement by, so two tables are only compared when they were measured on the same thing.</summary>
public sealed record BenchMachine(string Date, string Name, int Processors, string Operating, string Configuration, string Commit, int Runs)
{
    /// <summary>This machine, with the commit read from git where git is there and the build is in a working copy.</summary>
    public static BenchMachine Here(int runs, string? commit = null) => new(
        DateTime.Now.ToString("yyyy-MM-dd", CultureInfo.InvariantCulture),
        Environment.MachineName,
        Environment.ProcessorCount,
        Environment.OSVersion.VersionString,
#if DEBUG
        "Debug",
#else
        "Release",
#endif
        commit ?? "not named",
        runs);
}
