using System.Globalization;
using GroupLab.Core.Gltd.Binary;
using GroupLab.Core.Gltd.Model;
using GroupLab.Core.Rendering;
using GroupLab.Core.Rendering.Pdf;

namespace GroupLab.Core.Reporting;

/// <summary>
/// The volunteer print pack, NOTES-FROM-PLANNING.md entry 113 section 5: a sheet and one page of instructions, generated by GroupLab from the
/// Markdown source in docs/VOLUNTEER-PACK.md, which is embedded so the page and the document cannot drift. The page is set at the sheet's own
/// paper size, so the two print together, and the distance from bull 1 to bull 5 is the sheet's own. Consent is not in the pack: the upload
/// page collects it, and the page says submitting means following that page's terms.
/// </summary>
public static class VolunteerPack
{
    private const long Inch = 508;

    /// <summary>The Markdown the instruction page is set from.</summary>
    public static string Source()
    {
        using var stream = typeof(VolunteerPack).Assembly.GetManifestResourceStream("GroupLab.Core.Reporting.VolunteerPack.md")
            ?? throw new InvalidOperationException("The volunteer pack's source is not embedded.");
        using var reader = new StreamReader(stream);
        return reader.ReadToEnd();
    }

    /// <summary>The distance from bull 1 to bull 5 of a sheet, in inches and millimetres, or null when it has fewer than five scoring bulls.</summary>
    public static string? BullOneToFive(TargetDefinition definition)
    {
        ArgumentNullException.ThrowIfNull(definition);
        var scoring = definition.Bulls.Where(b => b.Scoring).ToList();
        if (scoring.Count < 5)
        {
            return null;
        }

        double dmm = Math.Sqrt(Math.Pow(scoring[4].X - scoring[0].X, 2) + Math.Pow(scoring[4].Y - scoring[0].Y, 2));
        return string.Create(CultureInfo.InvariantCulture, $"{dmm / 254:0.00} in ({dmm / 10:0.0} mm)");
    }

    /// <summary>
    /// The instruction page for a sheet: the Markdown's title, headings, bullets and paragraphs set in Helvetica on one page of the sheet's
    /// size. A pack that would run past one page is refused, since a volunteer is given one page.
    /// </summary>
    public static Scene Page(TargetDefinition definition, long width, long height, string? markdown = null)
    {
        ArgumentNullException.ThrowIfNull(definition);
        string text = (markdown ?? Source()).Replace("{bull-1-to-5}", BullOneToFive(definition) ?? "four times the distance between neighbouring bulls", StringComparison.Ordinal);
        var items = new List<SceneItem>();
        long margin = 3 * Inch / 5, right = width - margin, y = margin;
        var ink = new Rgb(20, 20, 20);
        var grey = new Rgb(70, 70, 70);
        var rule = new Rgb(190, 190, 190);
        long Pt(double points) => (long)Math.Round(points * Inch / 72);
        void Lines(string line, long size, Rgb colour, long indent, string? bullet)
        {
            var wrapped = ReportWriter.Wrap(line, size, right - margin - indent);
            for (int i = 0; i < wrapped.Count; i++)
            {
                y += size * 5 / 4;
                if (i == 0 && bullet is not null)
                {
                    items.Add(new TextRun(SceneLayer.Labels, colour, margin + indent - Pt(10), y - (size / 4), size, bullet, TextAnchor.Left));
                }

                items.Add(new TextRun(SceneLayer.Labels, colour, margin + indent, y - (size / 4), size, wrapped[i], TextAnchor.Left));
            }
        }

        foreach (string raw in text.Replace("\r\n", "\n", StringComparison.Ordinal).Split('\n'))
        {
            string line = raw.TrimEnd().Replace("**", "", StringComparison.Ordinal);
            if (line.Length == 0)
            {
                y += Pt(4);
            }
            else if (line.StartsWith("# ", StringComparison.Ordinal))
            {
                Lines(line[2..], Pt(18), ink, 0, null);
                y += Pt(2);
            }
            else if (line.StartsWith("## ", StringComparison.Ordinal))
            {
                y += Pt(4);
                Lines(line[3..], Pt(12.5), ink, 0, null);
                items.Add(new RectFill(SceneLayer.Labels, rule, margin, y + 6, right - margin, 3));
                y += Pt(3);
            }
            else if (line.StartsWith("- ", StringComparison.Ordinal))
            {
                Lines(line[2..], Pt(10), grey, Pt(14), "-");
            }
            else
            {
                Lines(line, Pt(10), grey, 0, null);
            }
        }

        items.Add(new TextRun(SceneLayer.Name, grey, margin, height - (margin / 2), Pt(7.5), ReportWriter.Plain($"For {definition.Name}"), TextAnchor.Left));
        if (y > height - margin)
        {
            throw new InvalidOperationException("The volunteer pack's instructions run past one page; shorten docs/VOLUNTEER-PACK.md.");
        }

        return new Scene(width, height, 0, items);
    }

    /// <summary>The pack as one PDF: every page of the sheet as rendered, then the instruction page at the sheet's size.</summary>
    public static byte[] Write(TargetDefinition definition, IReadOnlyList<Scene> sheet)
    {
        ArgumentNullException.ThrowIfNull(sheet);
        if (sheet.Count == 0)
        {
            throw new ArgumentException("The pack needs the sheet's pages.", nameof(sheet));
        }

        return PdfWriter.Write([.. sheet, Page(definition, sheet[0].Width, sheet[0].Height)]);
    }
}
