<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <EmbeddedResource Include="Gltd\Schema\gltd-1.schema.json" LogicalName="GroupLab.Core.Gltd.Schema.gltd-1.schema.json" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="GroupLab.Core.Tests" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Net.Codecrete.QrCodeGenerator" Version="3.2.1" />
  </ItemGroup>

</Project>
