using System.Reflection;

namespace GroupLab.Core.Statistics;

/// <summary>The range statistics of docs/STATISTICS.md section 5, and Rayleigh sigma, as columns of the range-statistic table.</summary>
public enum RangeStatistic
{
    /// <summary>The largest distance between two shots.</summary>
    ExtremeSpread,

    /// <summary>The mean of the bounding box's width and height.</summary>
    FigureOfMerit,

    /// <summary>The bounding box's diagonal.</summary>
    Diagonal,

    /// <summary>Rayleigh sigma, section 3.2, whose column exists for the efficiency comparison of section 5.</summary>
    RayleighSigma,
}

/// <summary>
/// GroupLab's range-statistic table, generated by <c>grouplab stats range-table</c> and embedded in Core, docs/STATISTICS.md
/// sections 5 and 15.3. It holds n from 2 to 50 and every fifth n to 100, crossed with 1 to 10 groups, and it is read between
/// its rows as shotGroups reads <c>DFdistr</c>: through a cubic spline in n with Forsythe, Malcolm and Moler's end conditions,
/// R's <c>splinefun</c> default, fitted to each column at each group count. Beyond 100 shots or 10 groups it has nothing, and
/// every lookup there returns no value rather than an extrapolated one.
/// </summary>
public sealed class RangeStatisticsTable
{
    private static readonly Lazy<RangeStatisticsTable> Embedded = new(() =>
    {
        using var stream = Assembly.GetExecutingAssembly().GetManifestResourceStream("GroupLab.Core.Statistics.RangeStatistics.csv")
            ?? throw new InvalidOperationException("the range-statistic table is not embedded; run grouplab stats range-table.");
        using var reader = new StreamReader(stream);
        return Parse(reader);
    });

    private readonly Dictionary<int, List<RangeTableRow>> byGroups;

    private RangeStatisticsTable(IEnumerable<RangeTableRow> rows)
    {
        byGroups = rows.GroupBy(r => r.Groups).ToDictionary(g => g.Key, g => g.OrderBy(r => r.N).ToList());
    }

    /// <summary>The table Core ships.</summary>
    public static RangeStatisticsTable Default => Embedded.Value;

    public static RangeStatisticsTable Parse(TextReader reader)
    {
        ArgumentNullException.ThrowIfNull(reader);
        var rows = new List<RangeTableRow>();
        for (string? line = reader.ReadLine(); line is not null; line = reader.ReadLine())
        {
            if (line.Length > 0 && !line.StartsWith('#') && !line.StartsWith("n,", StringComparison.Ordinal))
            {
                rows.Add(RangeTableRow.Parse(line));
            }
        }

        return new RangeStatisticsTable(rows);
    }

    /// <summary>The distribution of <paramref name="statistic"/> for groups of <paramref name="n"/> shots averaged over <paramref name="groups"/> groups, sigma 1; null outside the table.</summary>
    public RangeMoments? Lookup(RangeStatistic statistic, int n, int groups = 1)
    {
        if (!byGroups.TryGetValue(groups, out var rows) || n < rows[0].N || n > rows[^1].N)
        {
            return null;
        }

        RangeMoments Column(RangeTableRow row) => statistic switch
        {
            RangeStatistic.ExtremeSpread => row.ExtremeSpread,
            RangeStatistic.FigureOfMerit => row.FigureOfMerit,
            RangeStatistic.Diagonal => row.Diagonal,
            _ => row.RayleighSigma,
        };

        var exact = rows.FirstOrDefault(r => r.N == n);
        if (exact is not null)
        {
            return Column(exact);
        }

        double[] xs = [.. rows.Select(r => (double)r.N)];
        double At(Func<RangeMoments, double> field) => SplineFmm(xs, [.. rows.Select(r => field(Column(r)))], n);
        return new RangeMoments(At(m => m.Mean), At(m => m.Sd), At(m => m.Q025), At(m => m.Q975));
    }

    /// <summary>
    /// The value at <paramref name="x"/> of the cubic spline through the points, with the end conditions of Forsythe, Malcolm and
    /// Moler (the third derivative at each end matched to that of the cubic through the four nearest points), as R's
    /// <c>spline_coef</c> computes it for <c>method = "fmm"</c>.
    /// </summary>
    internal static double SplineFmm(double[] x, double[] y, double at)
    {
        int n = x.Length;
        var b = new double[n];
        var c = new double[n];
        var d = new double[n];
        int last = n - 1;
        d[0] = x[1] - x[0];
        c[1] = (y[1] - y[0]) / d[0];
        for (int i = 1; i < last; i++)
        {
            d[i] = x[i + 1] - x[i];
            b[i] = 2 * (d[i - 1] + d[i]);
            c[i + 1] = (y[i + 1] - y[i]) / d[i];
            c[i] = c[i + 1] - c[i];
        }

        b[0] = -d[0];
        b[last] = -d[n - 2];
        c[0] = c[last] = 0;
        if (n > 3)
        {
            c[0] = (c[2] / (x[3] - x[1])) - (c[1] / (x[2] - x[0]));
            c[last] = (c[n - 2] / (x[last] - x[n - 3])) - (c[n - 3] / (x[n - 2] - x[n - 4]));
            c[0] = c[0] * d[0] * d[0] / (x[3] - x[0]);
            c[last] = -c[last] * d[n - 2] * d[n - 2] / (x[last] - x[n - 4]);
        }

        for (int i = 1; i <= last; i++)
        {
            double t = d[i - 1] / b[i - 1];
            b[i] -= t * d[i - 1];
            c[i] -= t * c[i - 1];
        }

        c[last] /= b[last];
        for (int i = n - 2; i >= 0; i--)
        {
            c[i] = (c[i] - (d[i] * c[i + 1])) / b[i];
        }

        b[last] = ((y[last] - y[n - 2]) / d[n - 2]) + (d[n - 2] * (c[n - 2] + (2 * c[last])));
        for (int i = 0; i < last; i++)
        {
            b[i] = ((y[i + 1] - y[i]) / d[i]) - (d[i] * (c[i + 1] + (2 * c[i])));
            d[i] = (c[i + 1] - c[i]) / d[i];
            c[i] = 3 * c[i];
        }

        c[last] = 3 * c[last];
        d[last] = d[n - 2];
        int found = Array.BinarySearch(x, at);
        int k = Math.Clamp(found >= 0 ? found : ~found - 1, 0, last);
        double dx = at - x[k];
        return y[k] + (dx * (b[k] + (dx * (c[k] + (dx * d[k])))));
    }
}

/// <summary>
/// What a range statistic says, docs/STATISTICS.md section 5, through <see cref="RangeStatisticsTable"/>: its interval, the
/// sigma and CEP it implies, and its efficiency against Rayleigh sigma. These reproduce shotGroups' <c>getRangeStat</c>,
/// <c>range2sigma</c>, <c>range2CEP</c> and <c>getRangeStatEff</c>, so a shooter with a lifetime of extreme spreads has the
/// bridge section 5 asks for. Every one returns NaN where the table has no row, beyond 100 shots or 10 groups.
/// </summary>
public static class RangeStatistics
{
    /// <summary>
    /// The observed statistic with its 95 percent interval: the statistic scaled by the table's 2.5 and 97.5 percent quantiles
    /// over its mean, which is what shotGroups' <c>getRangeStat</c> reports.
    /// </summary>
    public static Estimate Interval(RangeStatistic statistic, double observed, int n, int groups = 1, RangeStatisticsTable? table = null)
    {
        var m = (table ?? RangeStatisticsTable.Default).Lookup(statistic, n, groups);
        return m is { } cell ? new Estimate(observed, observed * cell.Q025 / cell.Mean, observed * cell.Q975 / cell.Mean) : new Estimate(observed, double.NaN, double.NaN);
    }

    /// <summary>Sigma from a range statistic: the statistic over the table's mean, with the interval from its quantiles, shotGroups' <c>range2sigma</c>.</summary>
    public static Estimate Sigma(RangeStatistic statistic, double observed, int n, int groups = 1, RangeStatisticsTable? table = null)
    {
        var m = (table ?? RangeStatisticsTable.Default).Lookup(statistic, n, groups);
        return m is { } cell ? new Estimate(observed / cell.Mean, observed / cell.Q975, observed / cell.Q025) : new Estimate(double.NaN, double.NaN, double.NaN);
    }

    /// <summary>The circular CEP at <paramref name="level"/> from a range statistic, the implied sigma scaled by sqrt(-2 ln(1 - level)), shotGroups' <c>range2CEP</c>.</summary>
    public static Estimate Cep(RangeStatistic statistic, double observed, int n, int groups = 1, double level = 0.5, RangeStatisticsTable? table = null)
    {
        var sigma = Sigma(statistic, observed, n, groups, table);
        double k = Math.Sqrt(-2 * SpecialFunctions.Log1P(-level));
        return new Estimate(sigma.Value * k, sigma.Lower * k, sigma.Upper * k);
    }

    /// <summary>
    /// The efficiency of a statistic, shotGroups' <c>getRangeStatEff</c>: the squared ratio of its mean to its standard deviation
    /// per shot fired, M^2 / (n groups SD^2), so that the shots needed for a given relative precision scale inversely with it.
    /// </summary>
    public static double Efficiency(RangeStatistic statistic, int n, int groups = 1, RangeStatisticsTable? table = null)
    {
        var m = (table ?? RangeStatisticsTable.Default).Lookup(statistic, n, groups);
        return m is { } cell ? cell.Mean * cell.Mean / ((double)n * groups * cell.Sd * cell.Sd) : double.NaN;
    }
}
