using System.Globalization;
using GroupLab.Core.Statistics;

namespace GroupLab.Cli.Spike;

/// <summary>
/// <c>grouplab stats range-table [from to [replications]]</c>: generates GroupLab's own range-statistic table, docs/STATISTICS.md
/// section 15.3, into <c>src/GroupLab.Core/Statistics/RangeStatistics.csv</c>, which Core embeds.
/// <para>
/// The grid is shotGroups' own, n from 2 to 50 and then every fifth n to 100, crossed with 1 to 10 groups, because between its
/// rows shotGroups reads the table through R's <c>splinefun</c> (docs/PHASE1-RESULTS.md M3), and GroupLab reads its table the
/// same way. The run is long, so it is resumable: each n is written as soon as it is done, an n already in the file is skipped,
/// and a range of n can be run on its own in the foreground, printing progress, per CONTRIBUTING.md.
/// </para>
/// </summary>
public static class StatsRangeTable
{
    /// <summary>The seed every table is generated from, so the checked-in file can be regenerated exactly.</summary>
    public const ulong Seed = 20260914;

    /// <summary>Where the table lives, relative to the repository root.</summary>
    public const string DefaultTable = "src/GroupLab.Core/Statistics/RangeStatistics.csv";

    public static IEnumerable<int> Grid => Enumerable.Range(2, 49).Concat(Enumerable.Range(11, 10).Select(i => i * 5));

    public static int Run(string table, int from, int to, long replications, TextWriter output)
    {
        ArgumentNullException.ThrowIfNull(output);
        var rows = File.Exists(table)
            ? File.ReadLines(table).Where(l => l.Length > 0 && !l.StartsWith('#') && !l.StartsWith("n,", StringComparison.Ordinal)).Select(RangeTableRow.Parse).ToList()
            : [];
        var clock = System.Diagnostics.Stopwatch.StartNew();
        foreach (int n in Grid.Where(n => n >= from && n <= to))
        {
            if (rows.Any(r => r.N == n))
            {
                output.WriteLine(string.Create(CultureInfo.InvariantCulture, $"n = {n}: already in the table, skipped"));
                continue;
            }

            var started = clock.Elapsed;
            var simulated = RangeStatisticsSimulation.Simulate(n, replications, Seed);
            rows.AddRange(simulated);
            Write(table, rows);
            var one = simulated[0];
            output.WriteLine(string.Create(CultureInfo.InvariantCulture,
                $"[{clock.Elapsed.TotalSeconds,7:0}s] n = {n}: {replications:N0} replications in {(clock.Elapsed - started).TotalSeconds:0.0} s; one group ES mean {one.ExtremeSpread.Mean:0.00000} sd {one.ExtremeSpread.Sd:0.00000} 95% {one.ExtremeSpread.Q025:0.00000} to {one.ExtremeSpread.Q975:0.00000}, RS mean {one.RayleighSigma.Mean:0.00000}"));
            output.Flush();
        }

        output.WriteLine(string.Create(CultureInfo.InvariantCulture, $"done in {clock.Elapsed.TotalMinutes:0.0} minutes; {rows.Select(r => r.N).Distinct().Count()} of {Grid.Count()} n in {table}"));
        return 0;
    }

    private static void Write(string table, List<RangeTableRow> rows)
    {
        var lines = new List<string>
        {
            "# GroupLab range-statistic table, docs/STATISTICS.md sections 5 and 15.3. Generated by `grouplab stats range-table` with seed 20260914.",
            "# Groups of n shots from a circular bivariate normal with sigma 1, statistics averaged over nGroups groups: ES extreme spread,",
            "# FoM figure of merit, D bounding-box diagonal, RS Rayleigh sigma with the c4 correction. M mean, SD standard deviation, Q025 and Q975 quantiles.",
            RangeTableRow.Header,
        };
        lines.AddRange(rows.OrderBy(r => r.Groups).ThenBy(r => r.N).Select(r => r.ToCsv()));
        string temporary = table + ".tmp";
        File.WriteAllLines(temporary, lines);
        File.Move(temporary, table, overwrite: true);
    }
}
