using System.Globalization;
using System.Text;
using GroupLab.Core.Gltd.Binary;
using GroupLab.Core.Rendering;
using GroupLab.Core.Rendering.Pdf;

namespace GroupLab.Core.Marking;

/// <summary>
/// The calibre input's diameters and the rule it reads by, generated from <see cref="Calibre"/> so it cannot fall behind it:
/// <c>grouplab calibres</c> writes <c>docs/CALIBRES.md</c> and <c>docs/CALIBRES.pdf</c>, and a test fails when the committed Markdown differs
/// from what this produces (NOTES-FROM-PLANNING.md entry 106 section 4). Since entry 107 section 1 the input takes a diameter and no names, so
/// the list is the pick list's diameters in both units and the rule in plain words. The Markdown is the source; the PDF is drawn from it by
/// the renderer's own PDF writer.
/// </summary>
public static class CalibreList
{
    /// <summary>The list as Markdown.</summary>
    public static string Markdown()
    {
        var md = new StringBuilder();
        void Line(string text = "") => md.Append(text).Append('\n');
        Line("# Calibers in GroupLab");
        Line();
        Line("The caliber is entered as a cartridge name or as the bullet's diameter. Generated by `grouplab calibers` from `src/GroupLab.Core/Marking/Caliber.cs`; do not edit it by hand, because a test fails when this file differs from what the command writes.");
        Line();
        Line("## 1. How to enter a caliber");
        Line();
        Line("Type the cartridge's name, such as 6.5 Creedmoor, 308 or 9mm, or the bullet's diameter in inches, such as .264 or 0.264, or in millimeters with mm, such as 6.71 mm. **A name is matched before a number** (entry 163 section 3): 6.5 is the 6.5 mm family, 0.264 in, and not 6.5 mm, and .38 is 0.357 in, and not 0.380. As you type, GroupLab lists the cartridges it knows with their diameter beside them, the common first, and under the first it names the family you could pick by mistake.");
        Line();
        Line("Only what matches no name is read as a diameter. A designation that names no family in the table is refused rather than read as a diameter, because it is a name written as a number: 7.62 mm could be three different bullets. The designations refused when they name no family are, in inches, "
            + Join(Calibre.InchDesignations, v => v.ToString(".00#", CultureInfo.InvariantCulture))
            + ", and in millimeters, "
            + Join(Calibre.MillimetreDesignations, v => v.ToString("0.##", CultureInfo.InvariantCulture) + " mm")
            + ". A bare number of one or more that names nothing, such as 7.62 or 22, is refused for the same reason. Every diameter must lie between 0.1 and 1 in.");
        Line();
        Line("A designation's refusal names the problem, for example: \"" + Calibre.DesignationRefusal("7.62 mm") + "\"");
        Line();
        Line("A refusal says what to type: \"" + Calibre.Refusal + "\"");
        Line();
        Line("## 2. The cartridges GroupLab knows by name");
        Line();
        Line("Generated from `src/GroupLab.Core/Marking/cartridges.json`. Every cartridge here is confirmed at its diameter by both of these sources, and a cartridge only one confirms is held in section 3 until a second does:");
        Line();
        foreach (var (letter, source) in CartridgeTable.Sources.OrderBy(s => s.Key, StringComparer.Ordinal))
        {
            Line("- **" + letter + "**: " + source);
        }

        Line();
        Line("| Bullet | Family | Cartridges | Easily mistaken for |");
        Line("|---|---|---|---|");
        foreach (var family in CartridgeTable.Families.OrderBy(f => f.Diameter))
        {
            string traps = family.Traps.Count == 0 ? "" : string.Join(", ", family.Traps.Select(d => d.ToString("0.000", CultureInfo.InvariantCulture) + " in"));
            Line(string.Create(CultureInfo.InvariantCulture,
                $"| {family.Diameter:0.000} in ({family.Diameter * 25.4:0.00} mm) | {family.Name} | {string.Join(", ", family.Cartridges.Select(c => c.Name))} | {traps} |"));
        }

        Line();
        Line("## 3. Held back until a second source agrees");
        Line();
        Line("Typing one of these works as it did before names were read: GroupLab asks for the diameter. Where the two sources disagree, that is why the cartridge is here, and it is said.");
        Line();
        Line("| Cartridge | Diameter held | Sources | Why |");
        Line("|---|---|---|---|");
        foreach (var held in CartridgeTable.Held)
        {
            string sources = held.Sources.Count == 0 ? "none yet" : string.Join(", ", held.Sources);
            Line(string.Create(CultureInfo.InvariantCulture,
                $"| {held.Name} | {held.Diameter:0.000} in | {sources} | {held.Note ?? (held.Sources.Count < 2 ? "one source" : "")} |"));
        }

        Line();
        Line("## 4. The diameters in the pick list");
        Line();
        Line("Every distinct bullet diameter in Alan's rifle and pistol lists, smallest first. Any other diameter in range can be typed.");
        Line();
        Line("| Inches | Millimeters |");
        Line("|---|---|");
        foreach (double inches in Calibre.Diameters.Order())
        {
            Line(string.Create(CultureInfo.InvariantCulture, $"| {inches.ToString(".000#", CultureInfo.InvariantCulture)} | {inches * 25.4:0.00} |"));
        }

        Line();
        Line("## 5. Why names came back");
        Line();
        Line("Alan decided in entry 107 that the caliber is a diameter and nothing else, reversing entries 105 and 106, which read names through a table whose defects all came from reading a name as a diameter. Entry 108 refused the designations a person might type as a diameter. **Entry 163 reverses both, on the evidence of the first real user**: a person who shoots a 6.5 Creedmoor typed 6.5 and was offered .257, because the pick list matched 6.53 mm. A name he knows is a better thing to ask for than a diameter he does not, provided the table is right, which is why every name in it has two sources and every disagreement between them keeps the name out.");
        return md.ToString();
    }

    private static string Join(IEnumerable<decimal> values, Func<decimal, string> format)
    {
        var shown = values.Select(format).ToList();
        return string.Join(", ", shown.Take(shown.Count - 1)) + " and " + shown[^1];
    }

    // The PDF's page and type in the renderer's units, half-dmm, which are 0.05 mm (PdfWriter.PointsPerUnit): a Letter page, 18 mm margins,
    // and Helvetica, the one face the writer has, at 10 points for the body, 14 for headings and 18 for the title; a point is about 7 units.
    private const long PageWidth = 4318, PageHeight = 5588, MarginX = 360, MarginTop = 400, MarginBottom = 400;
    private const long Body = 70, Heading = 99, Title = 127, Leading = 36, CellGap = 100;
    private static readonly Rgb Ink = new(0x1a, 0x1c, 0x20);
    private static readonly Rgb Rule = new(0xbd, 0xb9, 0xb0);

    /// <summary>A cell's text broken into lines no wider than its column, at spaces.</summary>
    private static List<string> Wrap(string text, long width)
    {
        var lines = new List<string>();
        var line = new StringBuilder();
        foreach (string word in text.Split(' '))
        {
            string attempt = line.Length == 0 ? word : line + " " + word;
            if (HelveticaMetrics.TextWidth(attempt, Body) > width && line.Length > 0)
            {
                lines.Add(line.ToString());
                line.Clear().Append(word);
            }
            else
            {
                line.Clear().Append(attempt);
            }
        }

        lines.Add(line.ToString());
        return lines;
    }

    /// <summary>
    /// The PDF drawn from the Markdown <see cref="Markdown"/> writes: headings, paragraphs wrapped to the page, and tables in columns sized to
    /// their widest cell, the widest wrapped when a table is wider than the page, over as many Letter pages as it needs.
    /// </summary>
    public static byte[] Pdf(string markdown) => PdfWriter.Write(Pages(markdown));

    /// <summary>The PDF's pages as scenes, which the test holds inside the page's margins.</summary>
    public static IReadOnlyList<Scene> Pages(string markdown)
    {
        ArgumentNullException.ThrowIfNull(markdown);
        var pages = new List<Scene>();
        var items = new List<SceneItem>();
        long y = MarginTop;
        void NewPage()
        {
            pages.Add(new Scene(PageWidth, PageHeight, 0, [.. items]));
            items.Clear();
            y = MarginTop;
        }

        void Need(long height)
        {
            if (y + height > PageHeight - MarginBottom)
            {
                NewPage();
            }
        }

        void Text(string text, long size, long x = MarginX)
        {
            Need(size + Leading);
            y += size;
            items.Add(new TextRun(SceneLayer.Labels, Ink, x, y, size, text, TextAnchor.Left));
            y += Leading;
        }

        string Plain(string text) => text.Replace("`", "", StringComparison.Ordinal);

        void Paragraph(string text, long size)
        {
            var line = new StringBuilder();
            foreach (string word in Plain(text).Split(' '))
            {
                string attempt = line.Length == 0 ? word : line + " " + word;
                if (HelveticaMetrics.TextWidth(attempt, size) > PageWidth - (2 * MarginX) && line.Length > 0)
                {
                    Text(line.ToString(), size);
                    line.Clear().Append(word);
                }
                else
                {
                    line.Clear().Append(attempt);
                }
            }

            if (line.Length > 0)
            {
                Text(line.ToString(), size);
            }
        }

        var lines = markdown.Replace("\r", "", StringComparison.Ordinal).Split('\n');
        for (int i = 0; i < lines.Length; i++)
        {
            string line = lines[i];
            if (line.StartsWith("# ", StringComparison.Ordinal))
            {
                Text(line[2..], Title);
                y += Leading;
            }
            else if (line.StartsWith("## ", StringComparison.Ordinal))
            {
                y += Leading * 2;
                Text(line[3..], Heading);
            }
            else if (line.StartsWith('|'))
            {
                var table = new List<string[]>();
                for (; i < lines.Length && lines[i].StartsWith('|'); i++)
                {
                    if (!lines[i].StartsWith("|---", StringComparison.Ordinal))
                    {
                        table.Add([.. lines[i].Trim('|').Split('|').Select(c => Plain(c.Trim()))]);
                    }
                }

                i--;
                // Columns take their widest cell, and while the table is wider than the page the widest column is capped and its cells wrap.
                long available = PageWidth - (2 * MarginX) - (CellGap * (table[0].Length - 1));
                long[] widths = [.. Enumerable.Range(0, table[0].Length).Select(c => table.Max(r => HelveticaMetrics.TextWidth(r[c], Body)))];
                while (widths.Sum() > available)
                {
                    int widest = Array.IndexOf(widths, widths.Max());
                    widths[widest] = Math.Max(300, available - (widths.Sum() - widths[widest]));
                    if (widths.Sum() > available && widths[widest] == 300)
                    {
                        break;
                    }
                }

                for (int r = 0; r < table.Count; r++)
                {
                    var cells = table[r].Select((text, c) => Wrap(text, widths[c])).ToList();
                    int height = cells.Max(c => c.Count);
                    Need((height * (Body + (Leading / 2))) + Leading);
                    long top = y;
                    long x = MarginX;
                    for (int c = 0; c < cells.Count; c++)
                    {
                        for (int k = 0; k < cells[c].Count; k++)
                        {
                            items.Add(new TextRun(SceneLayer.Labels, Ink, x, top + Body + (k * (Body + (Leading / 2))), Body, cells[c][k], TextAnchor.Left));
                        }

                        x += widths[c] + CellGap;
                    }

                    y = top + (height * (Body + (Leading / 2))) + (Leading / 2);
                    if (r == 0)
                    {
                        items.Add(new RectFill(SceneLayer.Labels, Rule, MarginX, y, x - MarginX - CellGap, 4));
                    }

                    y += Leading / 2;
                }
            }
            else if (line.Length > 0)
            {
                Paragraph(line, Body);
            }
            else
            {
                y += Leading;
            }
        }

        NewPage();
        return pages;
    }
}
