using System.Globalization;
using System.Text;
using GroupLab.Core.Gltd.Binary;
using GroupLab.Core.Rendering;
using GroupLab.Core.Rendering.Pdf;

namespace GroupLab.Core.Marking;

/// <summary>
/// The calibre input's diameters and the rule it reads by, generated from <see cref="Calibre"/> so it cannot fall behind it:
/// <c>grouplab calibres</c> writes <c>docs/CALIBRES.md</c> and <c>docs/CALIBRES.pdf</c>, and a test fails when the committed Markdown differs
/// from what this produces (NOTES-FROM-PLANNING.md entry 106 section 4). Since entry 107 section 1 the input takes a diameter and no names, so
/// the list is the pick list's diameters in both units and the rule in plain words. The Markdown is the source; the PDF is drawn from it by
/// the renderer's own PDF writer.
/// </summary>
public static class CalibreList
{
    /// <summary>The list as Markdown.</summary>
    public static string Markdown()
    {
        var md = new StringBuilder();
        void Line(string text = "") => md.Append(text).Append('\n');
        Line("# Calibres in GroupLab");
        Line();
        Line("The calibre is entered as the bullet's diameter, and nothing else. Generated by `grouplab calibres` from `src/GroupLab.Core/Marking/Calibre.cs`; do not edit it by hand, because a test fails when this file differs from what the command writes.");
        Line();
        Line("## 1. How to enter a calibre");
        Line();
        Line("Type the bullet diameter in inches, such as .308 or 0.308, or in millimetres with mm, such as 7.82 mm. A number marked in or with an inch mark is inches too. A bare number of one or more, such as 7.62, 308 or 22, is refused rather than guessed, because a calibre's name is usually not its bullet's diameter: read as millimetres, 7.62 would be 0.300 in, which no 7.62 bullet is. Names such as 300 Blackout, 6.5 Creedmoor, 30 Cal. or 9mm are refused for the same reason. Every diameter must lie between 0.1 and 1 in.");
        Line();
        Line("A refusal says what to type: \"" + Calibre.Refusal + "\"");
        Line();
        Line("## 2. The diameters in the pick list");
        Line();
        Line("Every distinct bullet diameter in Alan's rifle and pistol lists, smallest first. Any other diameter in range can be typed.");
        Line();
        Line("| Inches | Millimetres |");
        Line("|---|---|");
        foreach (double inches in Calibre.Diameters.Order())
        {
            Line(string.Create(CultureInfo.InvariantCulture, $"| {inches.ToString(".000#", CultureInfo.InvariantCulture)} | {inches * 25.4:0.00} |"));
        }

        Line();
        Line("## 3. Why there are no names");
        Line();
        Line("Alan decided that the calibre is a diameter and nothing else (`docs/NOTES-FROM-PLANNING.md` entry 107 section 1), reversing entries 105 and 106, which read names through a table. Every defect those entries fixed came from reading a name as a diameter, and every name the table did not know still fell back to a guess. A diameter has one meaning.");
        return md.ToString();
    }

    // The PDF's page and type in the renderer's units, half-dmm, which are 0.05 mm (PdfWriter.PointsPerUnit): a Letter page, 18 mm margins,
    // and Helvetica, the one face the writer has, at 10 points for the body, 14 for headings and 18 for the title; a point is about 7 units.
    private const long PageWidth = 4318, PageHeight = 5588, MarginX = 360, MarginTop = 400, MarginBottom = 400;
    private const long Body = 70, Heading = 99, Title = 127, Leading = 36, CellGap = 100;
    private static readonly Rgb Ink = new(0x1a, 0x1c, 0x20);
    private static readonly Rgb Rule = new(0xbd, 0xb9, 0xb0);

    /// <summary>A cell's text broken into lines no wider than its column, at spaces.</summary>
    private static List<string> Wrap(string text, long width)
    {
        var lines = new List<string>();
        var line = new StringBuilder();
        foreach (string word in text.Split(' '))
        {
            string attempt = line.Length == 0 ? word : line + " " + word;
            if (HelveticaMetrics.TextWidth(attempt, Body) > width && line.Length > 0)
            {
                lines.Add(line.ToString());
                line.Clear().Append(word);
            }
            else
            {
                line.Clear().Append(attempt);
            }
        }

        lines.Add(line.ToString());
        return lines;
    }

    /// <summary>
    /// The PDF drawn from the Markdown <see cref="Markdown"/> writes: headings, paragraphs wrapped to the page, and tables in columns sized to
    /// their widest cell, the widest wrapped when a table is wider than the page, over as many Letter pages as it needs.
    /// </summary>
    public static byte[] Pdf(string markdown) => PdfWriter.Write(Pages(markdown));

    /// <summary>The PDF's pages as scenes, which the test holds inside the page's margins.</summary>
    public static IReadOnlyList<Scene> Pages(string markdown)
    {
        ArgumentNullException.ThrowIfNull(markdown);
        var pages = new List<Scene>();
        var items = new List<SceneItem>();
        long y = MarginTop;
        void NewPage()
        {
            pages.Add(new Scene(PageWidth, PageHeight, 0, [.. items]));
            items.Clear();
            y = MarginTop;
        }

        void Need(long height)
        {
            if (y + height > PageHeight - MarginBottom)
            {
                NewPage();
            }
        }

        void Text(string text, long size, long x = MarginX)
        {
            Need(size + Leading);
            y += size;
            items.Add(new TextRun(SceneLayer.Labels, Ink, x, y, size, text, TextAnchor.Left));
            y += Leading;
        }

        string Plain(string text) => text.Replace("`", "", StringComparison.Ordinal);

        void Paragraph(string text, long size)
        {
            var line = new StringBuilder();
            foreach (string word in Plain(text).Split(' '))
            {
                string attempt = line.Length == 0 ? word : line + " " + word;
                if (HelveticaMetrics.TextWidth(attempt, size) > PageWidth - (2 * MarginX) && line.Length > 0)
                {
                    Text(line.ToString(), size);
                    line.Clear().Append(word);
                }
                else
                {
                    line.Clear().Append(attempt);
                }
            }

            if (line.Length > 0)
            {
                Text(line.ToString(), size);
            }
        }

        var lines = markdown.Replace("\r", "", StringComparison.Ordinal).Split('\n');
        for (int i = 0; i < lines.Length; i++)
        {
            string line = lines[i];
            if (line.StartsWith("# ", StringComparison.Ordinal))
            {
                Text(line[2..], Title);
                y += Leading;
            }
            else if (line.StartsWith("## ", StringComparison.Ordinal))
            {
                y += Leading * 2;
                Text(line[3..], Heading);
            }
            else if (line.StartsWith('|'))
            {
                var table = new List<string[]>();
                for (; i < lines.Length && lines[i].StartsWith('|'); i++)
                {
                    if (!lines[i].StartsWith("|---", StringComparison.Ordinal))
                    {
                        table.Add([.. lines[i].Trim('|').Split('|').Select(c => Plain(c.Trim()))]);
                    }
                }

                i--;
                // Columns take their widest cell, and while the table is wider than the page the widest column is capped and its cells wrap.
                long available = PageWidth - (2 * MarginX) - (CellGap * (table[0].Length - 1));
                long[] widths = [.. Enumerable.Range(0, table[0].Length).Select(c => table.Max(r => HelveticaMetrics.TextWidth(r[c], Body)))];
                while (widths.Sum() > available)
                {
                    int widest = Array.IndexOf(widths, widths.Max());
                    widths[widest] = Math.Max(300, available - (widths.Sum() - widths[widest]));
                    if (widths.Sum() > available && widths[widest] == 300)
                    {
                        break;
                    }
                }

                for (int r = 0; r < table.Count; r++)
                {
                    var cells = table[r].Select((text, c) => Wrap(text, widths[c])).ToList();
                    int height = cells.Max(c => c.Count);
                    Need((height * (Body + (Leading / 2))) + Leading);
                    long top = y;
                    long x = MarginX;
                    for (int c = 0; c < cells.Count; c++)
                    {
                        for (int k = 0; k < cells[c].Count; k++)
                        {
                            items.Add(new TextRun(SceneLayer.Labels, Ink, x, top + Body + (k * (Body + (Leading / 2))), Body, cells[c][k], TextAnchor.Left));
                        }

                        x += widths[c] + CellGap;
                    }

                    y = top + (height * (Body + (Leading / 2))) + (Leading / 2);
                    if (r == 0)
                    {
                        items.Add(new RectFill(SceneLayer.Labels, Rule, MarginX, y, x - MarginX - CellGap, 4));
                    }

                    y += Leading / 2;
                }
            }
            else if (line.Length > 0)
            {
                Paragraph(line, Body);
            }
            else
            {
                y += Leading;
            }
        }

        NewPage();
        return pages;
    }
}
