#!/usr/bin/env python3
"""The README's generated sections, from the files that already say the same things.

NOTES-FROM-PLANNING.md entry 244. Alan: "Please make sure the readme gets updated with each build." The parts of
README.md that change with every build are written here, between markers, from their one source each, so they
cannot drift from it:

    newest     the newest build, its date and its downloads               docs/RELEASE-NOTES.md
    whats-new  what the newest few builds changed that a person notices  docs/RELEASE-NOTES.md, website/features.json
    features   every feature, short, linked to the Features page         website/features.json
    plan       what must be true before the first beta or stable release docs/RELEASE-PLAN.md

The platform statement and its minimums table are written by scripts/platform-support.py, as before.

    python3 scripts/readme.py --write     rewrite README.md between its markers
    python3 scripts/readme.py --check     fail if a generated section is stale, or a new feature went unmentioned

**The nudge.** The hand-written parts stay hand-written. So --check also fails when a release note of kind "new"
has landed since the README's prose last changed and neither the feature list nor the prose names it: a sign the
prose describes an older GroupLab. It lists what is missing. A change only between the markers is not a change to
the prose, so regenerating the README does not silence it; editing the prose does.
"""

from __future__ import annotations

import argparse
import importlib.util
import json
import re
import subprocess
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent.parent
README = HERE / "README.md"
NOTES = HERE / "docs" / "RELEASE-NOTES.md"
FEATURES = HERE / "website" / "features.json"
PLAN = HERE / "docs" / "RELEASE-PLAN.md"

SITE = "https://grouplab.org"
RELEASES = "https://github.com/oRAirwolf/grouplab/releases"

# How many builds "What is new" shows.
NEWEST = 3

SOURCES = {
    "newest": "docs/RELEASE-NOTES.md",
    "whats-new": "docs/RELEASE-NOTES.md and website/features.json",
    "features": "website/features.json",
    "plan": "docs/RELEASE-PLAN.md",
}


def begin(name: str) -> str:
    return f"<!-- readme:{name}: generated by scripts/readme.py from {SOURCES[name]}; do not edit between these markers -->"


def end(name: str) -> str:
    return f"<!-- /readme:{name} -->"


def builds(text: str) -> list[dict]:
    """Every build in the release notes, newest first: its version, date, commit, train and noticed changes."""
    found = []
    for block in re.split(r"(?m)^## ", text.split("\n---\n", 1)[1])[1:]:
        head, _, body = block.partition("\n")
        m = re.search(r"\*\*(\d{4}-\d{2}-\d{2})\*\*, commit `([0-9a-f]+)`\. (\w+)\.", body)
        noticed = []
        if "**What you will notice**" in body:
            part = body.split("**What you will notice**", 1)[1]
            part = re.split(r"\n\*\*|\n\[Downloads|\n---", part, maxsplit=1)[0]
            noticed = [line[2:].strip() for line in part.splitlines() if line.startswith("- ")]
        found.append({"version": head.strip(), "date": m.group(1) if m else "", "commit": m.group(2) if m else "",
                      "train": m.group(3) if m else "", "noticed": noticed})
    return found


def features() -> dict:
    return json.loads(FEATURES.read_text(encoding="utf-8"))


def feature_for(note: str, book: dict) -> dict | None:
    """The feature a release note belongs to: the one whose own note is in it, as the site's build decides."""
    for f in book["features"]:
        notes = [f["note"]] if isinstance(f.get("note"), str) else list(f.get("note") or [])
        if any(n.lower() in note.lower() for n in notes):
            return f
    return None


# Entry 266: the Download section is one table by platform.
PLATFORMS = [
    ("Windows", [("Installer", "grouplab-setup-win-x64.exe"), ("Zip", "grouplab-win-x64.zip")]),
    ("macOS", [("Apple silicon", "grouplab-macos-arm64.tar.gz"), ("Intel", "grouplab-macos-x64.tar.gz")]),
    ("Linux", [("Tarball", "grouplab-linux-x64.tar.gz")]),
    ("Android", [("APK", "grouplab-android.apk")]),
]
PLAY_TEST = "https://play.google.com/apps/internaltest/4701684356677501640"
# Entries 335 and 337, published with Alan's approval on 2026-10-01: the Microsoft Store listing and the TestFlight Public Beta.
STORE = "https://apps.microsoft.com/detail/9NWJCXBKZNPZ"
TESTFLIGHT = "https://testflight.apple.com/join/A3xyT6C6"


def newest() -> str:
    b = builds(NOTES.read_text(encoding="utf-8"))[0]
    rows = ["| Platform | Download |", "|---|---|"]
    for name, files in PLATFORMS:
        links = " · ".join(f"[{label}]({RELEASES}/download/nightly/{asset})" for label, asset in files)
        if name == "Windows":
            links += f" · [Microsoft Store]({STORE}), an older, steadier build that updates itself"
        if name == "Android":
            links += f" · [Google Play internal test]({PLAY_TEST}), by invitation"
        rows.append(f"| **{name}** | {links} |")
        if name == "macOS":
            rows.append(f"| **iPhone and iPad** | [Public beta on TestFlight]({TESTFLIGHT}): install TestFlight from the App Store, then open the invitation |")
    return (f"**The newest build is {b['version']}**, from {b['date']}, commit `{b['commit']}`: "
            f"[its release page]({RELEASES}/tag/v{b['version']}), and [what is new in it](#what-is-new).\n\n" + "\n".join(rows))


def whats_new() -> str:
    book = features()
    lines = []
    for b in builds(NOTES.read_text(encoding="utf-8"))[:NEWEST]:
        lines.append(f"**{b['version']}**, {b['date']}")
        lines.append("")
        if not b["noticed"]:
            lines.append("- Nothing you would notice; its changes are under the hood.")
        for note in b["noticed"]:
            f = feature_for(note, book)
            lines.append(f"- {note}" + (f" [{f['name']}]({SITE}/features/#{f['key']})" if f else ""))
        lines.append("")
    lines.append(f"Every build's notes are in [docs/RELEASE-NOTES.md](docs/RELEASE-NOTES.md) and at <{SITE}/releases/>.")
    return "\n".join(lines)


# Entry 266: three columns, each gathering the Features page's groups under it; every other group follows in one line.
COLUMNS = [
    ("Reads targets", ["Reading a target", "Photos and the phone"]),
    ("Honest statistics", ["The numbers"]),
    ("Prints sheets", ["Sheets and printing"]),
]


def feature_list() -> str:
    book = features()

    def named(groups: list[str]) -> str:
        return ", ".join(f"[{f['name']}]({SITE}/features/#{f['key']})" + (" (Android)" if f["platforms"] == ["Android"] else "")
                         for f in book["features"] if f["group"] in groups)

    lines = ["| " + " | ".join(f"**{title}**" for title, _ in COLUMNS) + " |", "|" + "---|" * len(COLUMNS)]
    lines.append("| " + " | ".join(named(groups) for _, groups in COLUMNS) + " |")
    lines.append("")
    rest = [g for g in book["groups"] if all(g not in groups for _, groups in COLUMNS)]
    for group in rest:
        if named([group]):
            lines.append(f"**{group}:** {named([group])}.")
            lines.append("")
    lines.append(f"Each one, with its picture, its platforms and the build it arrived in, is on the [Features page]({SITE}/features/).")
    return "\n".join(lines)


def plan() -> str:
    text = PLAN.read_text(encoding="utf-8")
    part = text.split("## What must be true first", 1)[1].split("\n## ", 1)[0]
    items, current = [], None
    for line in part.splitlines():
        if re.match(r"^\d+\. ", line):
            if current:
                items.append(current)
            current = line.strip()
        elif current is not None and line.startswith("   "):
            current += " " + line.strip()
        elif current is not None and not line.strip():
            items.append(current)
            current = None
    if current:
        items.append(current)
    return "\n".join(items)


MAKERS = {"newest": newest, "whats-new": whats_new, "features": feature_list, "plan": plan}


def section(text: str, name: str) -> tuple[int, int]:
    b, e = begin(name), end(name)
    if text.count(b) != 1 or text.count(e) != 1:
        raise SystemExit(f"README.md needs exactly one {b} and one {e}")
    start = text.index(b) + len(b)
    return start, text.index(e)


def generated(text: str) -> str:
    for name, make in MAKERS.items():
        start, stop = section(text, name)
        text = text[:start] + "\n" + make() + "\n" + text[stop:]
    return text


def prose(text: str) -> str:
    """The README without its generated sections, which is what a person writes."""
    for name in MAKERS:
        if begin(name) in text and end(name) in text:
            start, stop = section(text, name)
            text = text[:start] + text[stop:]
    return re.sub(r"<!-- platform-support.*?<!-- end platform-support -->", "", text, flags=re.S)


def git(*args: str) -> str:
    return subprocess.run(["git", *args], cwd=HERE, capture_output=True, text=True, encoding="utf-8").stdout


def last_prose_change() -> str | None:
    """The newest commit that changed the README's prose, not only its generated sections."""
    shas = git("log", "--format=%H", "-n", "200", "--", "README.md").split()
    for sha in shas:
        now = git("show", f"{sha}:README.md")
        before = git("show", f"{sha}^:README.md")
        if prose(now) != prose(before):
            return sha
    return None


def unmentioned() -> list[str]:
    """Release notes of kind new since the prose last changed that neither the feature list nor the prose names."""
    if git("rev-parse", "--is-shallow-repository").strip() == "true":
        print("readme: the history is shallow, so the check for new features the prose has not caught up with is skipped")
        return []
    since = last_prose_change()
    if since is None:
        return []
    spec = importlib.util.spec_from_file_location("release_notes", HERE / "scripts" / "release-notes.py")
    notes = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(notes)
    book, text = features(), prose(README.read_text(encoding="utf-8")).lower()
    missing = []
    for body in git("log", "--format=%B%x00", f"{since}..HEAD").split("\x00"):
        for note, kind in notes.reads(body):
            if kind != "new":
                continue
            f = feature_for(note, book)
            if f is None and not any(n.lower() in note.lower() and n.lower() in text for n in book.get("notFeatures", [])):
                missing.append(note)
    return missing


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    mode = parser.add_mutually_exclusive_group(required=True)
    mode.add_argument("--write", action="store_true")
    mode.add_argument("--check", action="store_true")
    args = parser.parse_args()
    raw = README.read_bytes().decode("utf-8")
    nl = "\r\n" if "\r\n" in raw else "\n"
    text = raw.replace("\r\n", "\n")
    fresh = generated(text)
    if args.write:
        if fresh != text:
            README.write_bytes(fresh.replace("\n", nl).encode("utf-8"))
            print("readme: rewritten")
        else:
            print("readme: already current")
        return 0

    failed = False
    if fresh != text:
        stale = [name for name in MAKERS if section(fresh, name) and fresh[slice(*section(fresh, name))] != text[slice(*section(text, name))]]
        print(f"readme: stale generated sections: {', '.join(stale)}. Run: python3 scripts/readme.py --write")
        failed = True
    missing = unmentioned()
    if missing:
        print("readme: new features have landed since the README's prose last changed, and neither the feature list nor the prose")
        print("names them. Revisit Status and the phase lists, and say what is new:")
        for note in missing:
            print(f"  - {note}")
        failed = True
    if not failed:
        print("readme: every generated section is current, and every new feature is named")
    return 1 if failed else 0


if __name__ == "__main__":
    sys.exit(main())
