#!/usr/bin/env python3
"""Rewrite every published build's entry in docs/RELEASE-NOTES.md, and optionally its GitHub release body.

NOTES-FROM-PLANNING.md entry 168 section 6. Alan: "Can you go back and fix all of the release notes?" Three
faults ran through them: notes cut off at the first line break, website and research items in an
application's notes, and a platform section frozen into release bodies that went stale the day it changed.

Each build is regenerated by scripts/release-notes.py from its own commits, against the build published
before it. What a person wrote by hand is kept: a **Known issues** section stays exactly as it is, and a
build whose trailers predate today's checks keeps the text it was published with, and is named.

**Nothing is deleted.** No release, asset or tag is touched; only the body text of each release.

    python3 scripts/rewrite-release-notes.py            rewrite docs/RELEASE-NOTES.md
    python3 scripts/rewrite-release-notes.py --github   and every release body on GitHub to match it
"""

from __future__ import annotations

import re
import subprocess
import sys
import tempfile
from pathlib import Path

HERE = Path(__file__).resolve().parent.parent
NOTES = HERE / "docs" / "RELEASE-NOTES.md"
DOWNLOAD = "https://grouplab.org/download/"


def run(*args: str) -> subprocess.CompletedProcess:
    return subprocess.run(list(args), cwd=HERE, capture_output=True, text=True)


def tags() -> list[str]:
    out = run("git", "tag", "--list", "v*-nightly.*").stdout.split()
    return sorted(out, key=lambda t: int(t.rsplit(".", 1)[1]))


def generated(tag: str, previous: str) -> str | None:
    """The notes the generator writes for one build now, without its own heading line, or None where it refuses."""
    done = run(sys.executable, "scripts/release-notes.py", tag.lstrip("v"), tag, previous)
    if done.returncode != 0:
        return None
    lines = done.stdout.strip().splitlines()
    return "\n".join(lines[1:]).strip() if lines and lines[0].startswith("GroupLab ") else done.stdout.strip()


def rewrite() -> tuple[list[str], list[str]]:
    text = NOTES.read_text(encoding="utf-8")
    ordered = tags()
    previous_of = {t: (ordered[i - 1] if i else "") for i, t in enumerate(ordered)}

    kept, rewritten = [], []

    def one(m: re.Match[str]) -> str:
        version, date, body, downloads = m.group("version"), m.group("date"), m.group("body"), m.group("downloads")
        tag = "v" + version
        known = re.search(r"^### Known issues\n.*", body, re.MULTILINE | re.DOTALL)
        fresh = generated(tag, previous_of.get(tag, "")) if tag in previous_of and previous_of[tag] else None
        if fresh is None:
            kept.append(version)
            return m.group(0)
        rewritten.append(version)
        out = f"## {version}\n\n{date}\n\n{fresh}\n\n"
        if known:
            out += known.group(0).rstrip() + "\n\n"
        return out + downloads

    pattern = re.compile(
        r"^## (?P<version>\d+\.\d+\.\d+-nightly\.\d+)\n\n(?P<date>\*\*[^\n]+)\n\n(?P<body>.*?)(?P<downloads>^\[Downloads for this build\]\([^)]*\)\n)",
        re.MULTILINE | re.DOTALL)
    text = pattern.sub(one, text)

    text = re.sub(
        r"Builds before 2026-09-23 use the older headings.*?on a board\.\n",
        "**Every entry was rewritten on 2026-09-24 from its build's own commits** (NOTES-FROM-PLANNING.md entry 168). "
        "Notes that had been cut off at a line break are whole again; website, research and documentation changes are "
        "gone from the builds, because they are not in the application and the website says when it changes; and a build "
        "that changed nothing in the application says so in one line and names the build it is the same as. **Known "
        "issues** sections are kept exactly as they were written. Two builds, " + ", ".join(kept_names := []) + " keep "
        "the text they were published with, because their notes were written before today's checks existed.\n",
        text, count=1, flags=re.DOTALL)

    text = re.sub(
        r"\*\*Why the nightly numbers skip\.\*\*.*?publishing again\.\n",
        "**Why the nightly numbers skip.** Up to nightly 91 a nightly was numbered by the workflow run that built it, and a "
        "run that was cancelled or skipped still took its number. From nightly 92 the number is the last published build "
        "plus one, so from there a gap means a number was never used, and a build that should not have been made is named "
        "as such below rather than hidden.\n",
        text, count=1, flags=re.DOTALL)

    NOTES.write_text(text, encoding="utf-8", newline="\n")
    return rewritten, kept


def entry(version: str) -> str:
    """One build's entry as it now stands in the file, without its heading."""
    text = NOTES.read_text(encoding="utf-8")
    m = re.search(rf"^## {re.escape(version)}\n\n(.*?)(?=^---\n|^## |\Z)", text, re.MULTILINE | re.DOTALL)
    return m.group(1).strip() if m else ""


def body_for(version: str, has_mac: bool) -> str:
    """What a release body says: the build's entry, and for a Mac build the one platform line."""
    body = f"GroupLab {version}.\n\n" + re.sub(r"\n*\[Downloads for this build\]\([^)]*\)\s*$", "", entry(version)).strip() + "\n"
    if has_mac:
        line = run(sys.executable, "scripts/platform-support.py", "--release").stdout.strip()
        body += "\n" + line + "\n"
    return body


ROLLING_TITLE = "Latest nightly (always the newest build, moves with every build)"


def rolling_body(version: str) -> str:
    """Entry 185 section 1: the rolling release says what it points at and repeats nothing, the same line the nightly writes."""
    return (f"The newest build, **{version}**. Its notes, the platform statement and its versioned downloads are on "
            f"[GroupLab {version}](https://github.com/oRAirwolf/grouplab/releases/tag/v{version}). "
            "This release moves to every new build, so its download addresses never change.\n")


def github(versions: list[str]) -> int:
    done = 0
    for version in versions + ["nightly"]:
        tag = "nightly" if version == "nightly" else "v" + version
        title: list[str] = []
        if version == "nightly":
            said = run("gh", "release", "view", "nightly", "--json", "name,body", "--jq", '.name + " " + .body').stdout
            named = re.search(r"GroupLab nightly, (\S+)", said) or re.search(r"The newest build, \*\*([^*]+)\*\*", said)
            if not named:
                print("nightly: not rewritten: its title and body name no build", file=sys.stderr)
                continue
            version = named.group(1).strip()
            body = rolling_body(version)
            title = ["--title", ROLLING_TITLE]
        else:
            assets = run("gh", "release", "view", tag, "--json", "assets", "--jq", ".assets[].name").stdout
            body = body_for(version, "grouplab-macos-" in assets)
        with tempfile.NamedTemporaryFile("w", suffix=".md", delete=False, encoding="utf-8") as f:
            f.write(body)
            path = f.name
        edited = run("gh", "release", "edit", tag, *title, "--notes-file", path)
        Path(path).unlink(missing_ok=True)
        if edited.returncode != 0:
            print(f"{tag}: not rewritten: {edited.stderr.strip()[:200]}", file=sys.stderr)
            continue
        done += 1
    print(f"{done} release bodies rewritten on GitHub")
    return done


def main() -> int:
    rewritten, kept = rewrite()
    # The two kept by name, now that they are known.
    text = NOTES.read_text(encoding="utf-8")
    names = " and ".join("nightly " + k.rsplit(".", 1)[1] for k in kept) if kept else "none"
    text = text.replace("Two builds, " + " keep the text", f"{'Two builds' if len(kept) == 2 else str(len(kept)) + ' builds'}, {names}, keep the text", 1)
    NOTES.write_text(text, encoding="utf-8", newline="\n")
    print(f"{len(rewritten)} entries rewritten in docs/RELEASE-NOTES.md, {len(kept)} kept as published: {', '.join(kept)}")
    if "--github" in sys.argv:
        github([t.lstrip("v") for t in tags()])
    return 0


if __name__ == "__main__":
    sys.exit(main())
